# Generated by Django 4.1 on 2024-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sellers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Paid", "Paid"), ("Completed", "Completed")],
                default="COMPLETED BUT NOT PAID",
                max_length=200,
                null=True,
            ),
        ),
    ]
